# Generated by Django 6.0.3 on 2026-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('steam_price', models.FloatField(default=0.0)),
                ('skinport_price', models.FloatField(default=0.0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
