# Generated by Django 6.0.3 on 2026-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='bitskins_price',
            field=models.FloatField(default=0.0),
        ),
    ]
