# Generated by Django 6.0.3 on 2026-03-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='SkinportData',
        ),
    ]
