# Generated by Django 6.0.3 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_data_skinportdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_items_list', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skinportdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
