# Generated by Django 6.0.3 on 2026-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_steamdata_skinportdata_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitskinsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_items_list', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
